[features]
seeds = false
[programs.devnet]
nft_marketplace = "AEHCDXMxQaKMEXECQRAzUjy1ewW6PNnP7KC9uQRzY9jk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/joec/.config/solana/nft-marketplace.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
app = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/**/*.ts"
