[features]
seeds = false
[programs.localnet]
pdas = "BtSZDMEWUNjHi38dqbxf1qxBahf4vtUn8HurZxSE85px"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/joec/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
