[features]
seeds = false
[programs.localnet]
nft_collection = "DTLBF55gymzA3jkWEZKud1KoHBX7aLvHxG7Qecp3pBi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/joec/.config/solana/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"
